[Personal]
source        = imaps://connortsullivan1%40gmail.com:wgjnxmwiadtrxjdq@imap.gmail.com:993
outgoing      = smtp://connortsullivan1%40gmail.com:wgjnxmwiadtrxjdq@smtp.gmail.com:587
default       = INBOX
from          = Connor Sullivan <connortsullivan1@gmail.com>
cache-headers = true
